[package]
name = "dagre-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dagre_rust = "0.0.5"
graphlib_rust = "0.0.2"
serde = "1.0.189"
serde_json = "1.0.107"
wasm-bindgen = "0.2.87"
